
const array = [
    {
        username: "B120001",
        password: "$2a$10$0Y4f4oEwgbu/V4.czQgOrOL2KrcTPS01JEbEjdRx7HQOg9SeNYS82",
        avatar: "man1",
        cover: "cover1.jpg",
        name: "Student 1",
        email : "b120001@iiit-bh.ac.in",
        contact: "+91 54321 67890",
        branch:"CSE",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.",
        education: ["Secondary school"],
        skills: ["C", "C++", "Javascrit", "WebDev"],
        achievements: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum."
    },
    {
        username: "B120002",
        password: "$2a$10$0Y4f4oEwgbu/V4.czQgOrOL2KrcTPS01JEbEjdRx7HQOg9SeNYS82",
        avatar: "man2",
        cover: "cover2.jpg",
        name: "Student 2",
        email : "b120002@iiit-bh.ac.in",
        contact: "+91 54321 67890",
        branch: "CSE",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.",
        education: ["Secondary school"],
        skills: ["C", "C++", "Python", "AI/ML"],
        achievements: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum."
    },
    {
        username: "B120003",
        password: "$2a$10$0Y4f4oEwgbu/V4.czQgOrOL2KrcTPS01JEbEjdRx7HQOg9SeNYS82",
        avatar: "woman1",
        cover: "cover3.jpg",
        name: "Student 3",
        email : "b120003@iiit-bh.ac.in",
        contact: "+91 54321 67890",
        branch: "CSE",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.",
        education: ["Secondary school"],
        skills: ["C", "C++", "Kotlin", "Andriod dev"],
        achievements: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum."
    },
    {
        username: "B120004",
        password: "$2a$10$0Y4f4oEwgbu/V4.czQgOrOL2KrcTPS01JEbEjdRx7HQOg9SeNYS82",
        avatar: "man3",
        cover: "cover2.jpg",
        name: "Student 4",
        email : "b120004@iiit-bh.ac.in",
        contact: "+91 54321 67890",
        branch: "CSE",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.",
        education: ["Secondary school"],
        skills: ["C", "C++", "Java", "Competitive Programming"],
        achievements: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum."
    },
    {
        username: "B120005",
        password: "$2a$10$0Y4f4oEwgbu/V4.czQgOrOL2KrcTPS01JEbEjdRx7HQOg9SeNYS82",
        avatar: "woman2",
        cover: "cover1.jpg",
        name: "Student 5",
        email : "b120005@iiit-bh.ac.in",
        contact: "+91 54321 67890",
        branch: "CSE",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.",
        education: ["Secondary school"],
        skills: ["C", "C++", "Javascrit", "WebDev"],
        achievements: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum."
    },
    {
        username: "B120006",
        password: "$2a$10$0Y4f4oEwgbu/V4.czQgOrOL2KrcTPS01JEbEjdRx7HQOg9SeNYS82",
        avatar: "woman3",
        cover: "cover3.jpg",
        name: "Student 6",
        email : "b120006@iiit-bh.ac.in",
        contact: "+91 54321 67890",
        branch:"CSE",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.",
        education: ["Secondary school"],
        skills: ["C", "C++", "Kotlin", "Andriod dev"],
        achievements: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum."
    },
    {
        username: "B120007",
        password: "$2a$10$0Y4f4oEwgbu/V4.czQgOrOL2KrcTPS01JEbEjdRx7HQOg9SeNYS82",
        avatar: "man4",
        cover: "cover3.jpg",
        name: "Student 7",
        email : "b120007@iiit-bh.ac.in",
        contact: "+91 54321 67890",
        branch:"CSE",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.",
        education: ["Secondary school"],
        skills: ["C", "C++", "Java", "Competitive Programming"],
        achievements: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum."
    },
    {
        username: "B120008",
        password: "$2a$10$0Y4f4oEwgbu/V4.czQgOrOL2KrcTPS01JEbEjdRx7HQOg9SeNYS82",
        avatar: "woman4",
        cover: "cover2.jpg",
        name: "Student 8",
        email : "b120008@iiit-bh.ac.in",
        contact: "+91 54321 67890",
        branch:"CSE",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.",
        education: ["Secondary school"],
        skills: ["C", "C++", "Javascrit", "WebDev"],
        achievements: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum."
    },
    {
        username: "B120009",
        password: "$2a$10$0Y4f4oEwgbu/V4.czQgOrOL2KrcTPS01JEbEjdRx7HQOg9SeNYS82",
        avatar: "woman5",
        cover: "cover1.jpg",
        name: "Student 9",
        email : "b120009@iiit-bh.ac.in",
        contact: "+91 54321 67890",
        branch:"CSE",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.",
        education: ["Secondary school"],
        skills: ["C", "C++", "Python", "AI/ML"],
        achievements: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum."
    },
    {
        username: "B120010",
        password: "$2a$10$0Y4f4oEwgbu/V4.czQgOrOL2KrcTPS01JEbEjdRx7HQOg9SeNYS82",
        avatar: "man5",
        cover: "cover3.jpg",
        name: "Student 10",
        email : "b120010@iiit-bh.ac.in",
        contact: "+91 54321 67890",
        branch:"CSE",
        about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum.",
        education: ["Secondary school"],
        skills: ["C", "C++", "Java", "Competitive Programming"],
        achievements: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, voluptatum."
    }
]

export default array